### ISSUE TITLE
Clean up on SIGTERM

### ISSUE THREAD

**Issue by ChrisBr** [SUSE/Enceladus#194]
As you know, we use ec2uploadimg as the "backend" for the OBS cloud uploader. We also provide the user the possibility to "abort" the upload which currently sends SIGTERM to ec2uploadimg which potentially leaves resources (e.g. helper instance, volumes etc) in AWS left.

I'm opening this issue to discuss some potential solutions to properly clean up when aborting the upload. 

One solution I'm currently trying is to install a [signal handler](https://docs.python.org/2/library/signal.html) in ec2uploadimg. 

```
def signal_handler(signal, frame):
    if uploader:
      uploader.clean_up()
    if setup:
      setup.clean_up()

signal.signal(signal.SIGTERM, signal_handler)
```

However, I don't really like this solution too much and also it seems it is not that reliable.

@rjschwei is a signal hanlder sth you would consider to include into ec2uploadimg? Do you have any other / better solution we could try out?

Thank you

**Comment by rjschwei** [comment]
@ChrisBr I am not opposed to a signal handler but it does have it's limitations. When invoked while we are in the middle of a transfer things are going to get really ugly because we are probably going to be in a place where it is difficult to clean up the sftp connection. Thus in order to do this cleanly with a signal handler we'd have to keep track of the stage of the image creation process and that will be a lot of overhead. Some examples:

- User aborts before upload starts:
  -> Easy, just kill the helper instance and clean up any created resources
- User aborts during image upload
  -> Not so easy, we should shut down the connection properly rather than just killing the receiving end and then cleaning up the ressources
- User aborts after snapshot is created but before image is registered
  -> Now what? Technically we'd have to remove the created snapshot.

I think it is cleaner to let the process run to the end and then clean up. Meaning we still have the signal handler but it just sets a flag on the uploader. The uploader checks the flag as it goes through its stages and then does "the right" thing. 

```
def signal_handler(signal, frame):
    uploader.abort()

signal.signal(signal.SIGTERM, signal_handler)
```
In the uploader itself:

```
def abort(self):
    """Set the abort flag to take appropriate action and stop image creation"""
    self.abort = True
```

Then in the "right" places

```
if self.abort:
......
```

**Comment by ChrisBr** [comment]
@rjschwei thanks a lot for your update. You're right, it is best to just set a flag and clean up in stages.

This is the approach I implemented for now:

- If the upload already started, we finish the current step and run the clean up afterwards.
- If the upload did not start but the setup process, we finish the setup, do not start an upload and clean up the setup afterwards (VPC etc).
- If neither setup nor upload started, we just exit.

See my PR for details

**Comment by rjschwei** [comment]
PR has been merged
